### PR TITLE
API calls and session usage

### LINKED ISSUE #3600: Huge Session table when using the API via Browser-Plugin
### Describe the issue

I have `kimai2_sessions` table of 1,2 GB.
We're using a custom Chrome browser-plugin to communicate with the API.

It looks like every request from the plugin is creating a new entry in the session table.

It's stated [here](https://www.kimai.org/documentation/rest-api.html) that plugins should use `X-AUTH-SESSION`, we'll try validating if this works.

Here's the corresponding line in the code:
https://github.com/kevinpapst/kimai2/blob/21dbfdb4f94ad25785cf753b405e131deb0fd29e/src/Security/TokenAuthenticator.php#L49-L51

Question: Is the "current session" show found in the database? Shouldn't API requests not create a session at all?

Additional question: How can I trigger an automatic or manual session-data cleanup?

CC: @handcode @eluhr

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kevinpapst/kimai2/discussions).

### Kimai version

1.15

### Which PHP version are you using?

7.4

### How do you run Kimai?

Self-Hosted

### Steps to reproduce the behavior

_No response_

### Logfile

_No response_

### Screenshots

_No response_

### Additional context

Device: any
Browser: Chrome (plugin)

### PR DESCRIPTION
**Pull request by kevinpapst**
## Description

adding a stateless firewall to prevent excessive session usage for API calls

Fixes #3600

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist
- [x] I verified that my code applies to the guidelines (`composer code-check`)
- [x] I agree that this code is used in Kimai and will be published under the [MIT license](https://github.com/kevinpapst/kimai2/blob/master/LICENSE)

### CODE REVIEW

**Comment by schmunk42** [comment]
Looks great and works!

**Comment by schmunk42** [comment]
Don't merge yet ... we're investigating an issue.

**Comment by kevinpapst** [comment]
What is 

> an issue

?

**Comment by schmunk42** [comment]
We need to investigate, it‘s likely on our side.

Von meinem iPhone gesendet

**Comment by kevinpapst** [comment]
Any news on the issue?

**Comment by schmunk42** [comment]
Yes and no :) One issue we had was insufficient permissions, which was related to the TaskManagement plugin.

For the rest ... we are testing atm.

**Comment by schmunk42** [comment]
It's ready to merge! :partying_face:

**Comment by kevinpapst** [comment]
Fantastico, thanks for the detailed tests 👍 und "Daumen drücken das alles gut geht" 😁

**Comment by schmunk42** [comment]
> Fantastico, thanks for the detailed tests +1 und "Daumen drücken das alles gut geht" grin

It's already running on our production system :grinning:

**Pull request merged**
