### PR TITLE
dashboard widgets are configurable via config

### PR DESCRIPTION
**Pull request by kevinpapst**
Added configurable dashboard widgets.

Widgets are in defined in kimai.yaml at `kimai.widgets` and the dashboard itself is configured at `kimai.dashboard`. The Katter one references widgets to display in each row, e.g.:

```yaml
kimai:
    dashboard:
        user:
            title: dashboard.you
            permission: ROLE_USER
            widgets: [userDurationToday, userDurationWeek, userDurationMonth, userDurationYear]

    widgets:
        userDurationToday: { title: stats.durationToday, query: duration, user: true, begin: '00:00:00', end: '23:59:59', icon: duration, color: green }
        userDurationWeek: { title: stats.durationWeek, query: duration, user: true, begin: 'monday this week 00:00:00', end: 'sunday this week 23:59:59', icon: duration, color: blue }
        userDurationMonth: { title: stats.durationMonth, query: duration, user: true, begin: 'first day of this month 00:00:00', end: 'last day of this month 23:59:59', icon: duration, color: purple }
        userDurationYear: { title: stats.durationYear, query: duration, user: true, begin: '01 january this year 00:00:00', end: '31 december this year 23:59:59', icon: duration, color: yellow }
        userDurationTotal: { title: stats.durationTotal, query: duration, user: true, icon: duration, color: red }
```

Now its possible to define the data inside the widgets by the person hosting Kimai 2.

You can simply overwrite the settings in `local.yaml`

```yaml
    dashboard:
        user: { widgets: [userDurationWeek, userDurationMonth, userDurationYear, userDurationTotal] }
```

There are some widgets pre-defined, which are not displayed.

See #207

**TODO**
- [x] add an embed and example for a chart
- [x] add documentation

### CODE REVIEW

**Comment by sideeffect42** [comment]
Thanks for having a go at this. Simply awesome, and exactly what I needed!

Is there a way to reorder the dashboard rows? I added a custom row in my `local.yaml`, but it's always displayed at the bottom.

**Comment by kevinpapst** [comment]
@sideeffect42 reordering is not possible, but you can simply overwrote one or all of the pre-configred sections by defining them in your `local.yaml` - I added a [documentation chapter about it](https://github.com/kevinpapst/kimai2/blob/b95dff2872ad7dcefd60e7dfbf95e06145222ce0/var/docs/dashboard.md) (right at the bottom).
Please check if that works for you.

**Comment by sideeffect42** [comment]
@kevinpapst Overwriting all the default sections does work, it is a bit of an unfortunate solution, tough.

I thought about how this could be solved, but couldn't think of a really good solution.
The best one I could come up with would be to prepend all names with an integer and then sorting the hash map before rendering it.

**Comment by kevinpapst** [comment]
@sideeffect42 please check out the latest commit with section ordering

**Comment by sideeffect42** [comment]
@kevinpapst Awesome. I really like the solution with the `order` property.

Another idea that came to my mind is that it would be really cool if the tiles could be filtered by customer.
I imagine that this wouldn't be too easy to implement, though.

**Comment by kevinpapst** [comment]
Customers would be great indeed, but please create a new feature request for this - so I can add it later.

**Comment by sideeffect42** [comment]
@kevinpapst Sure, just wanted to ask you first if you could think of such a feature. See #272.

**Comment by kevinpapst** [comment]
@sideeffect42 if you want to help, you could check the latest commit.
I added a chart widget which is not activated by default. Docu [is here](https://github.com/kevinpapst/kimai2/pull/269/commits/e6260e8dabed5465876e1667006f2a4448551749#diff-35e03ae5399d30e5d8bb72c7eee30ea4). Simply put that into your `local.yaml`:
```
kimai:
    widgets:
        userRecapTwoYears: { title: stats.durationToday, query: monthly, user: true, begin: '01 january last year 00:00:00', end: '31 december this year 23:59:59', color: '#3b8bba|rgba(0,115,183,0.6);#c1c7d1|rgb(210,214,222,0.9)' }

    dashboard:
        user_duration:
            type: chart
            widgets: [userRecapTwoYears, userDurationToday, userDurationWeek, userDurationMonth, userDurationYear]
```

**Pull request merged**
