### PR TITLE
Add emoji to terminal output at end of startup

### PR DESCRIPTION
**Pull request by vitormattos**
## Description
When I run in a container, the output at docker log is very cold, to give a best feedback to sysadmin/developers and be more happy, I added emojis signalizing the step of end of startup

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist
- [x] I verified that my code applies to the guidelines (`composer code-check`)
- [x] I updated the documentation (see [here](https://github.com/kimai/www.kimai.org/tree/master/_documentation))
- [x] I agree that this code is used in Kimai (see [license](https://github.com/kimai/kimai/blob/main/LICENSE))

### CODE REVIEW

**Comment by kevinpapst** [comment]
Sweet idea 👍 @tobybatch your choice

**Comment by vitormattos** [comment]
What you think about to put the follow `echo` in the end of `startup.sh`, before `exec /service.sh`?
```
🟡 startup.sh finished
```
Yellow because is attention and all the startup didn't finished yet.


By example:
<details>
<summary>Click here to expand the log</summary>

```log
🟡 startup.sh finished
Wait for MySQL DB connection ...
Testing DB:** new \PDO(mysql:host=db;dbname=kimai;port=3306, kimai, 2CXQ4utCMgRuTwusXkvixxkJ5viemCKaJzZ34YhwmLpdszivSq, [ \PDO::ATTR_ERRMODE => \PDO::ERRMODE_EXCEPTION ]);*Connection established

Kimai installation running ...
==============================

Database `kimai` for connection named default already exists. Skipped.

 [WARNING] You have 1 previously executed migrations in the database that are   
           not registered migrations.                                           

 >> 2023-01-23 19:47:00 (DoctrineMigrations\Version20993112235958)
[notice] Migrating up to DoctrineMigrations\Version20231130000719
[notice] finished in 653.8ms, used 24M memory, 3 migrations executed, 6 sql queries

 [OK] Successfully migrated to version: DoctrineMigrations\Version20231130000719



 Rebuilding your cache, please be patient ...

 // Clearing the cache for the prod environment with debug false                

 [OK] Cache for the "prod" environment (debug=false) was successfully cleared.  


 // Warming up the cache for the prod environment with debug false              

 [OK] Cache for the "prod" environment (debug=false) was successfully warmed.   


 [OK] Congratulations! Successfully installed Kimai version 2.5.0               


Kimai updates running ...
=========================

[2023-12-03T17:00:20.160807+00:00] deprecation.INFO: User Deprecated: Context: Passing values to option `--all-or-nothing` Problem: Passing values is deprecated Solution: If you need to disable the behavior, omit the option, otherwise, pass the option without a value (ConsoleInputMigratorConfigurationFactory.php:44 called by ConsoleInputMigratorConfigurationFactory.php:22, https://github.com/doctrine/migrations/issues/1304, package doctrine/migrations) {"exception":"[object] (ErrorException(code: 0): User Deprecated: Context: Passing values to option `--all-or-nothing`\nProblem: Passing values is deprecated\nSolution: If you need to disable the behavior, omit the option,\notherwise, pass the option without a value (ConsoleInputMigratorConfigurationFactory.php:44 called by ConsoleInputMigratorConfigurationFactory.php:22, https://github.com/doctrine/migrations/issues/1304, package doctrine/migrations) at /opt/kimai/vendor/doctrine/deprecations/lib/Doctrine/Deprecations/Deprecation.php:210)"} {"channel":"deprecation"}

 [WARNING] You have 1 previously executed migrations in the database that are   
           not registered migrations.                                           

 >> 2023-01-23 19:47:00 (DoctrineMigrations\Version20993112235958)

 [OK] Already at the latest version ("DoctrineMigrations\Version20993112235958")


 Rebuilding your cache, please be patient ...

 // Clearing the cache for the prod environment with debug false                

 [OK] Cache for the "prod" environment (debug=false) was successfully cleared.  


 // Warming up the cache for the prod environment with debug false              

 [OK] Cache for the "prod" environment (debug=false) was successfully warmed.   


 [OK] Congratulations! Successfully updated Kimai to version 2.5.0              


 [OK] Success! Created user: superadmin                                         

Kimai2 ready
 Validating config file syntax ...

 [OK] All 25 YAML files contain valid syntax.                                   


 [OK] All 629 XLIFF files contain valid syntax.                                 


 Rebuilding your cache, please be patient ...

 // Clearing the cache for the prod environment with debug false                

 [OK] Cache for the "prod" environment (debug=false) was successfully cleared.  


 // Warming up the cache for the prod environment with debug false              

 [OK] Cache for the "prod" environment (debug=false) was successfully warmed.   


 [OK] Kimai config was reloaded                                                 

🏁 Running 🐘 php-fpm server
```
</details>

And, congratulations by this work!
I love a lot to contribute to open source projects that maintain all the code open.

**Comment by vitormattos** [comment]
@kevinpapst was your reaction <3 an approve about the question that I exposed or a like to the congratulations?

I ask because if is an approve, I will add a new commit at this PR because I think that is the same context.

**Comment by kevinpapst** [comment]
I am not maintaining nor want to decide about such docker changes -> we have to wait for @tobybatch to answer.
My ❤️ was meant for your last two sentences.

**Review by tobybatch — APPROVED** [review]
My only reservation is if this is running on a service that doesn't support extended character sets we'll get

Selection_314

But that'll be limited to things like xterm. I don't know about things like remote consoles in places like AWS but I guess it's such an edge case we'll go with the change and see if we get any complaints.

**Comment by kevinpapst** [comment]
@vitormattos do you have any example of popular docker images that does the same?

**Comment by vitormattos** [comment]
@tobybatch sounds that this is a limitation of your terminal. If you get the same log in a terminal that have fonts with emoji or that render unicode chars, will work fine.

I don't remember about production images, but have development images that do this because is important to developers analyze logs and if have emojis, help a bit.

Is possible to see here an example of Nextcloud development environment:
https://github.com/juliushaertl/nextcloud-docker-dev/blob/master/bootstrap.sh

**Comment by kevinpapst** [comment]
I have seen so many bugs in my life, caused by such innocent changes.
I love the idea and thanks for the idea @vitormattos but this time I am closing in favor of the cold but "proven to work" output.

**Pull request closed without merging**
