### PR TITLE
Translations update from Hosted Weblate

### PR DESCRIPTION
**Pull request by yangyangdaji**
replace kimai#3945
fix https://github.com/kimai/kimai/pull/3945#discussion_r1148347390

### CODE REVIEW

**Comment by kevinpapst** [comment]
Thank you @yangyangdaji for your continuous support, I really appreciate that 👍 

But could you please do the changes at Weblate? I cannot compare the two PRs and if I merge your PR all changes at Weblate will be lost, components locked due to changes on both sides... will be a nightmare .. I made that mistake a couple of times and really want to avoid it 😁 

What exactly did you change here?

**Comment by yangyangdaji** [comment]
> 
Because I don’t know which source string should be changed, all of which are "users", but I didn’t find the "User Name" string

**Comment by yangyangdaji** [comment]
Is this it?
https://hosted.weblate.org/translate/kimai/messages/es/?checksum=60dd54e10539ce15



---Original---
From: ***@***.***&gt;
Date: Tue, Mar 28, 2023 21:57 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [kimai/kimai] Translations update from Hosted Weblate (PR #3951)




 
Codecov Report
  
Merging #3951 (a99b35a) into main (04b5eb4) will decrease coverage by 0.01%.
 The diff coverage is n/a.
  Additional details and impacted files @@             Coverage Diff              @@ ##               main    #3951      +/-   ## ============================================ - Coverage     89.15%   89.15%   -0.01%        Complexity     8223     8223               ============================================   Files           745      745                 Lines         27830    27830               ============================================ - Hits          24812    24811       -1      - Misses         3018     3019       +1     
 
see 1 file with indirect coverage changes

**Comment by kevinpapst** [comment]
You (can but) don't need to check the PRs, I will add feedback in Weblate if necessary.
I can change tiny things like that by myself. Actually I just leave these comments, so I know that I have to check something. 
And I didn't expect anyone else looking into it.
Let me check, I'll let you know. If have to check again if it is just a historical mistake that two strings exist and they should both be translated as `User` or if the keys `user` and `username` should be a difference.

**Comment by yangyangdaji** [comment]
ok&nbsp;



---Original---
From: "Kevin ***@***.***&gt;
Date: Tue, Mar 28, 2023 22:19 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [kimai/kimai] Translations update from Hosted Weblate (PR #3951)




 
You (can but) don't need to check the PRs, I will add feedback in Weblate if necessary.
 I can change tiny things like that by myself. Actually I just leave these comments, so I know that I have to check something.
 And I didn't expect anyone else looking into it.
 Let me check, I'll let you know. If have to check again if it is just a historical mistake that two strings exist and they should both be translated as User or if the keys user and username should be a difference.

**Comment by yangyangdaji** [comment]
> You (can but) don't need to check the PRs, I will add feedback in Weblate if necessary. I can change tiny things like that by myself. Actually I just leave these comments, so I know that I have to check something. And I didn't expect anyone else looking into it. Let me check, I'll let you know. If have to check again if it is just a historical mistake that two strings exist and they should both be translated as `User` or if the keys `user` and `username` should be a difference.


ok

**Comment by yangyangdaji** [comment]
@kevinpapst feel free to dispose of this pr

**Comment by kevinpapst** [comment]
closing in favor of #3945

Thanks @yangyangdaji 🚀

**Pull request closed without merging**
