### PR TITLE
Feature/colored select2 component issue 3109

### PR DESCRIPTION
**Pull request by kulturbande**
## Description
Show the color in the timesheet edit form for customer, project, and activity. This is a good way to select the correct entry if you have multiple e.g. activities with the same name (and maybe different rates). 

Issue Reference https://github.com/kevinpapst/kimai2/issues/3109

Example:
Aufnahme 2022-02-20 at 21 06 50@2x

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist
- [ ] I verified that my code applies to the guidelines (`composer code-check`)
- [ ] I updated the documentation (see [here](https://github.com/kimai/www.kimai.org/tree/master/_documentation))
- [x] I agree that this code is used in Kimai and will be published under the [MIT license](https://github.com/kevinpapst/kimai2/blob/master/LICENSE)

### CODE REVIEW

**Comment by kevinpapst** [comment]
I like the changes in general and the try to simplify the code by re-using the color attribute.
But: I'd prefer if the existing markup for the "colored dot" would be re-used. 
Then we would need the support for `data-renderer=color-dot` and `data-renderer=color`.

**Comment by kulturbande** [comment]
Sure, that would make sense. I was reusing only the previous select solution, but I can have a look if colored dot of the table is usable as well to make it "dryer".

**Comment by kulturbande** [comment]
I updated the usage of the `color-dot`:

- use a background instead of an icon
- use the same icon - class for the select2 options
- moved the definition of the `.color-dot` - class to a new utils.scss (I couldn't find a proper place)

Data Table:
Aufnahme 2022-02-22 at 22 27 20@2x

Timesheet Edit:
Aufnahme 2022-02-22 at 22 27 35@2x

**Comment by kulturbande** [comment]
@kevinpapst What do you think of the current implementation? Should it be improved or is it mergable?

**Comment by kulturbande** [comment]
@kevinpapst I rebased the branch to have the latest main - changes included

**Comment by kulturbande** [comment]
@kevinpapst Do you have any objections? I would rebase the master and resolve the current conflicts.

**Comment by kulturbande** [comment]
No worries! Keep me posted, then I rebase the branch again.

**Comment by kulturbande** [comment]
And thank you for your dedication!

**Comment by kulturbande** [comment]
I rebased and updated the PR to the latest master changes

**Comment by kulturbande** [comment]
I made a rebase with the latest master

**Comment by kevinpapst** [comment]
I think the idea is good, so let me keep this for a while.

**Comment by kulturbande** [comment]
Fair enough. I could also update to the latest master, but this is a bit exhausting, because the build increments changing quit offen.

**Comment by kevinpapst** [comment]
Leave it as is, I will get back to it and resolve the conflicts

**Comment by kevinpapst** [comment]
Short update:

I am working on the next major #2902 since quite a while and now we have several issues:
- it is using Tomselect instead of Select2 (I can adapt the code for it)
- the next major has the "random color" setting always active (which we should assume fr your PR as well)
- the API does return null on unset colors, which are likely the most

The last point is the biggest issue, as we cannot show a color upon select reload, which happens for project and activity if you choose a customer, or only activity if you select a project.

I wanted to replace all "null" with the color for the current object (it is not entirely random, but the color is calculated from the name, so it is "sticky random") in the AP, whichI I tried to do with with a JMS Serializer `SubscribingHandlerInterface`, but I couldn't get it to work. 
Now if someone has an idea how to do that, I will merge this PR into #2902

**Comment by kevinpapst** [comment]
Closing, needs re-write for #2902

**Pull request closed without merging**
