### PR TITLE
invoice calculator to group entries by activity

### LINKED ISSUE #334: Activities just Duration
A great Feature would be to have certain activities showing jsut the duration on the Invoice.

### PR DESCRIPTION
**Pull request by kevinpapst**
Fixes #334 and #379

### CODE REVIEW

**Comment by srdco** [comment]
It also said (in a red warning block):
```
In ArrayNode.php line 311:
                                                                           
  Unrecognized options "renderer, number_generator" under "kimai.invoice"
```

**Comment by kevinpapst** [comment]
Seems you were using 0.4 before, as these keys were removed in 0.5, see https://github.com/kevinpapst/kimai2/releases
You should update to 0.5 in the regular way before switching.

Do you have a local.yaml with these keys are stored?

**Comment by srdco** [comment]
Seems like it - I was just looking into that. I thought I'd updated, but must have missed something.
Can't find a local.yaml, and now Kimai is showing a blank screen again.

**Comment by kevinpapst** [comment]
Blank screen - the 500 of death is not good... check if there is something in var/logs/
Otherwise you need to check your server logs.

**Comment by srdco** [comment]
I'm getting this on everything I do:
```
PHP Notice:  Found invalid "kimai" configuration: Unrecognized options "renderer, number_generator" under "kimai.invoice" in /var/www/kimai2/src/DependencyInjection/AppExtension.php on line 32
PHP Notice:  Undefined index: languages in /var/www/kimai2/src/DependencyInjection/AppExtension.php on line 36
PHP Notice:  Undefined index: calendar in /var/www/kimai2/src/DependencyInjection/AppExtension.php on line 37
PHP Notice:  Undefined index: theme in /var/www/kimai2/src/DependencyInjection/AppExtension.php on line 38
PHP Notice:  Undefined index: dashboard in /var/www/kimai2/src/DependencyInjection/AppExtension.php on line 39
PHP Notice:  Undefined index: widgets in /var/www/kimai2/src/DependencyInjection/AppExtension.php on line 40
PHP Notice:  Undefined index: invoice in /var/www/kimai2/src/DependencyInjection/AppExtension.php on line 41
PHP Notice:  Undefined index: defaults in /var/www/kimai2/src/DependencyInjection/AppExtension.php on line 42
PHP Notice:  Undefined index: user in /var/www/kimai2/src/DependencyInjection/AppExtension.php on line 54
PHP Notice:  Undefined index: user in /var/www/kimai2/src/DependencyInjection/AppExtension.php on line 60
PHP Notice:  Undefined index: user in /var/www/kimai2/src/DependencyInjection/AppExtension.php on line 66
PHP Notice:  Undefined index: timesheet in /var/www/kimai2/src/DependencyInjection/AppExtension.php on line 75
PHP Notice:  Undefined index: timesheet in /var/www/kimai2/src/DependencyInjection/AppExtension.php on line 76
PHP Notice:  Undefined index: timesheet in /var/www/kimai2/src/DependencyInjection/AppExtension.php on line 77
PHP Notice:  Undefined index: timesheet in /var/www/kimai2/src/DependencyInjection/AppExtension.php on line 78
PHP Warning:  Invalid argument supplied for foreach() in /var/www/kimai2/src/DependencyInjection/Compiler/TwigContextCompilerPass.php on line 37

In ArrayNode.php line 311:
                                                                           
  Unrecognized options "renderer, number_generator" under "kimai.invoice"  
                                                                           
```

**Comment by srdco** [comment]
Also, here's the Kimai log:
[prod.log.txt](https://github.com/kevinpapst/kimai2/files/2532131/prod.log.txt)

**Comment by srdco** [comment]
I can't seem to find local.yaml in the /var/www/kimai2/ folder

**Comment by kevinpapst** [comment]
That log is a terrible mess, what did you do?
With a bit of luck this is the main reason:
```
[2018-10-06 18:46:14] console.ERROR: Error thrown while running command "--ansi cache:clear". Message: "Unable to write in the "/var/www/kimai2/var/cache/prod" directory" {"exception":"[object] (Symfony\\Component\\Console\\Exception\\RuntimeException(code: 0): Unable to write in the \"/var/www/kimai2/var/cache/prod\" directory at /var/www/kimai2/vendor/symfony/framework-bundle/Command/CacheClearCommand.php:88)","command":"--ansi cache:clear","message":"Unable to write in the \"/var/www/kimai2/var/cache/prod\" directory"} []
```
If not, please open a new issue for it, as this pull request is a completely different topic

**Pull request merged**
