### PR TITLE
link timesheets to invoices

### PR DESCRIPTION
**Pull request by kevinpapst**
## Description

Closes #2995 
Closes #2414 
See discussion https://github.com/kevinpapst/kimai2/discussions/2630

## Types of changes
- [x] New feature (non-breaking change which adds functionality)

## Checklist
- [x] I verified that my code applies to the guidelines (`composer code-check`)
- [x] I agree that this code is used in Kimai and will be published under the [MIT license](https://github.com/kevinpapst/kimai2/blob/master/LICENSE)

### CODE REVIEW

**Comment by kevinpapst** [comment]
@Conni2461 is that a feature that you actually require or can you already work with the adjusted InvoiceCreatedEvent, which now allows to fetch the entities of the invoice?

**Comment by Conni2461** [comment]
I'll need to check. I'll try to find some time for it this week.

Thanks for putting in all this work :)

**Comment by kevinpapst** [comment]
There is not much enough interest to implement that fully

**Comment by LiaraAlis** [comment]
Any chance to implement this after all? I'm happy to provide support here.

**Comment by kevinpapst** [comment]
Nope. Both concept and goals are unclear and merely anyone wants it.

**Comment by LiaraAlis** [comment]
To be honest I don't understand why not. It totally makes sense to link information to invoices that are needed to understand on what the invoice depends.
And it is required to make it possible to regenerate invoice documents or improve the invoicing process (generating credit documents and so on…).

**Pull request closed without merging**
